spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: first_service
#          uri: http://localhost:7788/
#          predicates:
#            - Path=/first/**
#
#        - id: second_service
#          uri: http://localhost:7789/
#          predicates:
#            - Path=/second/**

        - id: back_ehrbase
          uri: http://localhost:8888/
          predicates:
            - Path=/register/**


eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9999
